var b;b||=typeof Module != 'undefined' ? Module : {};var h=Object.assign({},b),m=(a,c)=>{throw c;},p="object"==typeof window,q="function"==typeof importScripts,t="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,v="",w,x,y;
if(t){var fs=require("fs"),z=require("path");v=q?z.dirname(v)+"/":__dirname+"/";w=(a,c)=>{a=A(a)?new URL(a):z.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};y=a=>{a=w(a,!0);a.buffer||(a=new Uint8Array(a));return a};x=(a,c,d,e=!0)=>{a=A(a)?new URL(a):z.normalize(a);fs.readFile(a,e?void 0:"utf8",(l,u)=>{l?d(l):c(e?u.buffer:u)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=b);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof B||a.context instanceof B))throw a;
});m=(a,c)=>{process.exitCode=a;throw c;}}else if(p||q)q?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),v=v.startsWith("blob:")?"":v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1),w=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},q&&(y=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),x=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",
a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};var ca=b.print||console.log.bind(console),C=b.printErr||console.error.bind(console);Object.assign(b,h);h=null;b.quit&&(m=b.quit);var D;b.wasmBinary&&(D=b.wasmBinary);var E,F=!1,G,H,I=[],J=[],da=[],K=[];function ea(){var a=b.preRun.shift();I.unshift(a)}var O=0,P=null,Q=null,R=a=>a.startsWith("data:application/octet-stream;base64,"),A=a=>a.startsWith("file://"),S;S="a.out.wasm";
if(!R(S)){var T=S;S=b.locateFile?b.locateFile(T,v):v+T}function U(a){if(a==S&&D)return new Uint8Array(D);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}function fa(a){if(!D&&(p||q)){if("function"==typeof fetch&&!A(a))return fetch(a,{credentials:"same-origin"}).then(c=>{if(!c.ok)throw`failed to load wasm binary file at '${a}'`;return c.arrayBuffer()}).catch(()=>U(a));if(x)return new Promise((c,d)=>{x(a,e=>c(new Uint8Array(e)),d)})}return Promise.resolve().then(()=>U(a))}
function V(a,c,d){return fa(a).then(e=>WebAssembly.instantiate(e,c)).then(d,e=>{C(`failed to asynchronously prepare wasm: ${e}`);b.onAbort?.(e);e="Aborted("+e+")";C(e);F=!0;throw new WebAssembly.RuntimeError(e+". Build with -sASSERTIONS for more info.");})}
function ha(a,c){var d=S;D||"function"!=typeof WebAssembly.instantiateStreaming||R(d)||A(d)||t||"function"!=typeof fetch?V(d,a,c):fetch(d,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(c,function(l){C(`wasm streaming compile failed: ${l}`);C("falling back to ArrayBuffer instantiation");return V(d,a,c)}))}function B(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var W=a=>{for(;0<a.length;)a.shift()(b)},ia=b.noExitRuntime||!0,ja=[null,[],[]],X="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,ka={b:(a,c,d)=>G.copyWithin(a,c,c+d),a:(a,c,d,e)=>{for(var l=0,u=0;u<d;u++){var na=H[c>>2],aa=H[c+4>>2];c+=8;for(var L=0;L<aa;L++){var f=G[na+L],M=ja[a];if(0===f||10===f){f=M;for(var k=0,n=k+NaN,r=k;f[r]&&!(r>=n);)++r;if(16<r-k&&f.buffer&&X)f=X.decode(f.subarray(k,r));else{for(n="";k<r;){var g=f[k++];if(g&128){var N=f[k++]&63;if(192==(g&224))n+=String.fromCharCode((g&
31)<<6|N);else{var ba=f[k++]&63;g=224==(g&240)?(g&15)<<12|N<<6|ba:(g&7)<<18|N<<12|ba<<6|f[k++]&63;65536>g?n+=String.fromCharCode(g):(g-=65536,n+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else n+=String.fromCharCode(g)}f=n}(1===a?ca:C)(f);M.length=0}else M.push(f)}l+=aa}H[e>>2]=l;return 0}},Y=function(){function a(d){Y=d.exports;E=Y.c;d=E.buffer;b.HEAP8=new Int8Array(d);b.HEAP16=new Int16Array(d);b.HEAPU8=G=new Uint8Array(d);b.HEAPU16=new Uint16Array(d);b.HEAP32=new Int32Array(d);b.HEAPU32=H=
new Uint32Array(d);b.HEAPF32=new Float32Array(d);b.HEAPF64=new Float64Array(d);J.unshift(Y.d);O--;b.monitorRunDependencies?.(O);0==O&&(null!==P&&(clearInterval(P),P=null),Q&&(d=Q,Q=null,d()));return Y}var c={a:ka};O++;b.monitorRunDependencies?.(O);if(b.instantiateWasm)try{return b.instantiateWasm(c,a)}catch(d){return C(`Module.instantiateWasm callback failed with error: ${d}`),!1}ha(c,function(d){a(d.instance)});return{}}(),la=b._main=(a,c)=>(la=b._main=Y.e)(a,c),Z;Q=function ma(){Z||oa();Z||(Q=ma)};
function oa(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!F)){W(J);W(da);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(pa){var c=la;try{var d=c(0,0);ia||(b.onExit?.(d),F=!0);m(d,new B(d))}catch(e){e instanceof B||"unwind"==e||m(1,e)}}if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)c=b.postRun.shift(),K.unshift(c);W(K)}}if(!(0<O)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ea();W(I);0<O||(b.setStatus?(b.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();var pa=!0;b.noInitialRun&&(pa=!1);oa();
